name: Update latest CSV 
on: 
  push:
    branches: [ main ]
jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Web Request Action
        id: goUkLink
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://www.gov.uk/api/content/government/publications/register-of-licensed-sponsors-workers
          method: GET
      - name: use output
        run: |
          $output = '${{ steps.goUkLink.data }}' | ConvertFrom-Json
          Write-Host "Url from output $($output.details.attachments.url)"
