name: Update latest CSV 
on: 
  schedule:
    - cron: 10 15 * * 0-6
jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: set output
        run: |
         echo ::set-output name=getUpdatedUrl:: curl https://www.gov.uk/api/content/government/publications/register-of-licensed-sponsors-workers
      - name: use output
        run: |
         echo $getUpdatedUrl | jq '.details.attachments.url'
        env:
          getUpdatedUrl: ${{ steps.set.outputs.getUpdatedUrl}}
